services:
  api-db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vyhul
    networks:
      - default

  api-redis:
    image: redis:7.4.1-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - default


networks:
  default:
    name: davidp-net

volumes:
  postgres-data:
  redis-data:
